### ISSUE TITLE
Road Plan

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/ManasCore#6]
1. Modification to 'stairsToBlock' in RecipeProvider to fit both Improved Stair Builder and Vanilla Stair Builder.
Working similarly to the 'stairs' builder, having a 'true' or 'false' boolean would determine which recipe it would make.

So in an actual case.
`        stairsToBlock(consumer, false, Blocks.OAK_STAIRS, Blocks.OAK_PLANKS); // < --- 2 Stairs = 3 Blocks`

2. Add a 'blasting' recipe builder and also update the 'allSmeltingRecipes' builder to include the blasting recipe. Passing a 'false' in one of the segments would not make a Recipe for that.

Currently, after you state the items you want, its EXP, Smelting, Campfire, Smoker.
The new change would be EXP, Smelting, Blasting, Campfire, Smoker.

Instead of having 2 lines if you wanted to do an ore, you could pass a 'false' in 2 of the sections, meaning it would look like
`        allSmeltingRecipes(consumer, Ingredient.of(Items.RAW_IRON), Items.IRON_INGOT, 0.35F, 200, 100, false, false);`

3. Once tested to ensure it works, update to the Gist (link below) aswell as Uploading the version to CurseForge.

4. Update to 1.19.2

**Comment by Nieadni** [comment]
https://gist.github.com/Nieadni/bbd1599f45d4bdc3d6b67e61e769a515

**Comment by Charismara** [comment]
_i might reopen this after the 1.19.2 port_
